syntax = "proto3";
option java_multiple_files = true;
package ds.tutorial.communication.grpc.generated;
message CheckBalanceRequest {
string accountId = 1;
}
message CheckBalanceResponse {
double balance = 1;
}
service CheckBalanceService {
rpc checkBalance(CheckBalanceRequest) returns (CheckBalanceResponse);
}

message SetBalanceRequest {
string accountId = 1;
double value = 2;
bool isSentByPrimary = 3;
}
message SetBalanceResponse {
bool status = 1;
}
service SetBalanceService {
rpc setBalance(SetBalanceRequest) returns (SetBalanceResponse);
}

message SetUpdateRequest {
string fromAccId = 1;
string toAccId = 2;
double value = 3;
bool isSentByPrimary = 4;
string transactionId = 5;
}
message SetUpdateResponse {
bool status = 1;
}
service SetUpdateService {
rpc setUpdate(SetUpdateRequest) returns (SetUpdateResponse);
}

message GetAllAccountsRequest {}

message GetAllAccountsResponse {
  map<string, double> accounts = 1;
}
service AccountSyncService {
  rpc GetAllAccounts (GetAllAccountsRequest) returns (GetAllAccountsResponse);
}

message SetCrossPartTransRequest{
string accId = 1;
double amount = 2;
bool isDebit =3;
bool isSentByPrimary = 4;
string txId = 5;
}
message SetCrossPartTransResponse{
bool status = 1;
}
service SetCrossPartTransService{
rpc setTransaction(SetCrossPartTransRequest) returns (SetCrossPartTransResponse);
}